# prune_config :
#### runner ####
freezed_finetune : 'camera'
freeze_epoch : 1
#### camera ####
target_ratio : 0.5
data_dependendcy : False
sparsity_learning : False
method : l1
global_pruning : False
soft_keeping_ratio : 0.0
reg : 1e-4
delta_reg : 1e-4
max_pruning_ratio : 1.0
sl_epochs : None
sl_resume : None
sl_lr : None
sl_lr_step_size : None
sl_lr_warmup_epochs : None